# Funding options for AntiStutter
# Remove or comment out any platforms you don't use

# GitHub Sponsors
github: # [DancingTedDanson011]

# Other platforms
# patreon: DancingTedDanson011
# open_collective: antistutter
# ko_fi: DancingTedDanson011
# liberapay: DancingTedDanson011
# custom: https://yourwebsite.com/donate

# Note: This project is free and open source.
# Donations are optional but appreciated to support development!
